// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT7BxEX5G1zjiXvycSHosUKLyFWJXGTtU',
    appId: '1:609096608184:web:6cde903f05d4e115a0474d',
    messagingSenderId: '609096608184',
    projectId: 'videoplayerappp',
    authDomain: 'videoplayerappp.firebaseapp.com',
    storageBucket: 'videoplayerappp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqK8H7tHNLi9Q_wMv63nHMzOdsMD9_-ug',
    appId: '1:609096608184:android:c38e9b235594b375a0474d',
    messagingSenderId: '609096608184',
    projectId: 'videoplayerappp',
    storageBucket: 'videoplayerappp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Qm09xwN5r5vmlVDG91hdvbKCPwnIMlo',
    appId: '1:609096608184:ios:af720fd283418333a0474d',
    messagingSenderId: '609096608184',
    projectId: 'videoplayerappp',
    storageBucket: 'videoplayerappp.appspot.com',
    iosClientId: '609096608184-18m3otv70spq84mlgbkuf8meaovu9l0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoplayerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Qm09xwN5r5vmlVDG91hdvbKCPwnIMlo',
    appId: '1:609096608184:ios:5f3fb21b648a657ea0474d',
    messagingSenderId: '609096608184',
    projectId: 'videoplayerappp',
    storageBucket: 'videoplayerappp.appspot.com',
    iosClientId: '609096608184-72e6gmnve1nrfbmddkp5jctks03f77r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoplayerapp.RunnerTests',
  );
}
